/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.lwjgl

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'lwjgl.greeting' plugin.
 */
class LwjglPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("elect86.lwjgl")

        // Verify the result
//        assertNotNull(project.tasks.findByName("lwjgl"))
    }
}
